level: info
interval: 0 # seconds
catnap:
  number: -1
  duration: 2 # minutes
sleep:
  number: -1
  duration: 30 # minutes
playlist:
  - 4234112
  - 4312424
accounts:
  - phone: 18267028869
    passwd: "su1317869280"
    code: 86
    expired: 2024-09-06
    only_sign: false
    unstable: false
